version: '3.8'
services:
  dev-db:
    image: postgres:13
    ports:
      - 5434:5432
    environment:
      POSTGRES_USER: mbs
      POSTGRES_PASSWORD: mbs
      POSTGRES_DB: mbs
    networks:
      - dev
networks: 
  dev:
